<?php

declare(strict_types=1);

namespace Database\Seeders;

class PrefixesTableSeeder extends JsonTableSeeder
{
    protected string $table = 'prefixes';

    protected ?int $autoIncrement = 570;

    /**
     * Data jsou drobná a statická (volací prefixy → země), takže žijí přímo
     * tady v těle místo v samostatném JSON snapshotu.
     *
     * @return list<array{id: int, prefix: string, country: string}>
     */
    protected function rows(): array
    {
        return [
            ['id' => 265, 'prefix' => 'DA', 'country' => 'Germany'],
            ['id' => 266, 'prefix' => 'DB', 'country' => 'Germany'],
            ['id' => 267, 'prefix' => 'DC', 'country' => 'Germany'],
            ['id' => 268, 'prefix' => 'DD', 'country' => 'Germany'],
            ['id' => 269, 'prefix' => 'DE', 'country' => 'Germany'],
            ['id' => 270, 'prefix' => 'DF', 'country' => 'Germany'],
            ['id' => 271, 'prefix' => 'DG', 'country' => 'Germany'],
            ['id' => 272, 'prefix' => 'DH', 'country' => 'Germany'],
            ['id' => 273, 'prefix' => 'DI', 'country' => 'Germany'],
            ['id' => 274, 'prefix' => 'DJ', 'country' => 'Germany'],
            ['id' => 275, 'prefix' => 'DK', 'country' => 'Germany'],
            ['id' => 276, 'prefix' => 'DL', 'country' => 'Germany'],
            ['id' => 277, 'prefix' => 'DM', 'country' => 'Germany'],
            ['id' => 278, 'prefix' => 'DN', 'country' => 'Germany'],
            ['id' => 279, 'prefix' => 'DO', 'country' => 'Germany'],
            ['id' => 280, 'prefix' => 'DP', 'country' => 'Germany'],
            ['id' => 281, 'prefix' => 'DQ', 'country' => 'Germany'],
            ['id' => 282, 'prefix' => 'DR', 'country' => 'Germany'],
            ['id' => 283, 'prefix' => 'I0', 'country' => 'Italy'],
            ['id' => 284, 'prefix' => 'IA', 'country' => 'Italy'],
            ['id' => 285, 'prefix' => 'IB', 'country' => 'Italy'],
            ['id' => 286, 'prefix' => 'IC', 'country' => 'Italy'],
            ['id' => 287, 'prefix' => 'ID', 'country' => 'Italy'],
            ['id' => 288, 'prefix' => 'IE', 'country' => 'Italy'],
            ['id' => 289, 'prefix' => 'IF', 'country' => 'Italy'],
            ['id' => 290, 'prefix' => 'IG', 'country' => 'Italy'],
            ['id' => 291, 'prefix' => 'IH', 'country' => 'Italy'],
            ['id' => 292, 'prefix' => 'II', 'country' => 'Italy'],
            ['id' => 293, 'prefix' => 'IJ', 'country' => 'Italy'],
            ['id' => 294, 'prefix' => 'IK', 'country' => 'Italy'],
            ['id' => 295, 'prefix' => 'IL', 'country' => 'Italy'],
            ['id' => 296, 'prefix' => 'IM', 'country' => 'Italy'],
            ['id' => 297, 'prefix' => 'IN', 'country' => 'Italy'],
            ['id' => 298, 'prefix' => 'IO', 'country' => 'Italy'],
            ['id' => 299, 'prefix' => 'IP', 'country' => 'Italy'],
            ['id' => 300, 'prefix' => 'IQ', 'country' => 'Italy'],
            ['id' => 301, 'prefix' => 'IR', 'country' => 'Italy'],
            ['id' => 302, 'prefix' => 'IS', 'country' => 'Sardinia'],
            ['id' => 303, 'prefix' => 'IT', 'country' => 'Sicily'],
            ['id' => 304, 'prefix' => 'IU', 'country' => 'Italy'],
            ['id' => 305, 'prefix' => 'IV', 'country' => 'Italy'],
            ['id' => 306, 'prefix' => 'IW', 'country' => 'Italy'],
            ['id' => 307, 'prefix' => 'IX', 'country' => 'Italy'],
            ['id' => 308, 'prefix' => 'IY', 'country' => 'Italy'],
            ['id' => 309, 'prefix' => 'IZ', 'country' => 'Italy'],
            ['id' => 311, 'prefix' => 'FB', 'country' => 'France'],
            ['id' => 312, 'prefix' => 'FC', 'country' => 'Corsica'],
            ['id' => 313, 'prefix' => 'FD', 'country' => 'France'],
            ['id' => 314, 'prefix' => 'FE', 'country' => 'France'],
            ['id' => 315, 'prefix' => 'FF', 'country' => 'France'],
            ['id' => 316, 'prefix' => 'FU', 'country' => 'France'],
            ['id' => 317, 'prefix' => 'FV', 'country' => 'France'],
            ['id' => 318, 'prefix' => 'TH', 'country' => 'France'],
            ['id' => 319, 'prefix' => 'TK', 'country' => 'Corsica'],
            ['id' => 320, 'prefix' => 'TM', 'country' => 'France'],
            ['id' => 321, 'prefix' => 'TO', 'country' => 'France'],
            ['id' => 322, 'prefix' => 'TQ', 'country' => 'France'],
            ['id' => 323, 'prefix' => 'TV', 'country' => 'France'],
            ['id' => 324, 'prefix' => 'TW', 'country' => 'France'],
            ['id' => 325, 'prefix' => 'TX', 'country' => 'France'],
            ['id' => 326, 'prefix' => 'R2', 'country' => 'Kaliningrad'],
            ['id' => 327, 'prefix' => 'RA2', 'country' => 'Kaliningrad'],
            ['id' => 328, 'prefix' => 'RB2', 'country' => 'Kaliningrad'],
            ['id' => 329, 'prefix' => 'RC2', 'country' => 'Kaliningrad'],
            ['id' => 330, 'prefix' => 'RD2', 'country' => 'Kaliningrad'],
            ['id' => 331, 'prefix' => 'RE2', 'country' => 'Kaliningrad'],
            ['id' => 332, 'prefix' => 'RF2', 'country' => 'Kaliningrad'],
            ['id' => 333, 'prefix' => 'RG2', 'country' => 'Kaliningrad'],
            ['id' => 334, 'prefix' => 'RH2', 'country' => 'Kaliningrad'],
            ['id' => 335, 'prefix' => 'RI2', 'country' => 'Kaliningrad'],
            ['id' => 336, 'prefix' => 'RJ2', 'country' => 'Kaliningrad'],
            ['id' => 337, 'prefix' => 'RK2', 'country' => 'Kaliningrad'],
            ['id' => 338, 'prefix' => 'RL2', 'country' => 'Kaliningrad'],
            ['id' => 339, 'prefix' => 'RM2', 'country' => 'Kaliningrad'],
            ['id' => 340, 'prefix' => 'RN2', 'country' => 'Kaliningrad'],
            ['id' => 341, 'prefix' => 'RO2', 'country' => 'Kaliningrad'],
            ['id' => 342, 'prefix' => 'RP2', 'country' => 'Kaliningrad'],
            ['id' => 343, 'prefix' => 'RQ2', 'country' => 'Kaliningrad'],
            ['id' => 344, 'prefix' => 'RR2', 'country' => 'Kaliningrad'],
            ['id' => 345, 'prefix' => 'RS2', 'country' => 'Kaliningrad'],
            ['id' => 346, 'prefix' => 'RT2', 'country' => 'Kaliningrad'],
            ['id' => 347, 'prefix' => 'RU2', 'country' => 'Kaliningrad'],
            ['id' => 348, 'prefix' => 'RV2', 'country' => 'Kaliningrad'],
            ['id' => 349, 'prefix' => 'RW2', 'country' => 'Kaliningrad'],
            ['id' => 350, 'prefix' => 'RX2', 'country' => 'Kaliningrad'],
            ['id' => 351, 'prefix' => 'RY2', 'country' => 'Kaliningrad'],
            ['id' => 352, 'prefix' => 'RZ2', 'country' => 'Kaliningrad'],
            ['id' => 353, 'prefix' => 'U2', 'country' => 'Kaliningrad'],
            ['id' => 354, 'prefix' => 'UA2', 'country' => 'Kaliningrad'],
            ['id' => 355, 'prefix' => 'UB2', 'country' => 'Kaliningrad'],
            ['id' => 356, 'prefix' => 'UC2', 'country' => 'Kaliningrad'],
            ['id' => 357, 'prefix' => 'UD2', 'country' => 'Kaliningrad'],
            ['id' => 358, 'prefix' => 'UE2', 'country' => 'Kaliningrad'],
            ['id' => 359, 'prefix' => 'UF2', 'country' => 'Kaliningrad'],
            ['id' => 360, 'prefix' => 'UG2', 'country' => 'Kaliningrad'],
            ['id' => 361, 'prefix' => 'UH2', 'country' => 'Kaliningrad'],
            ['id' => 362, 'prefix' => 'UI2', 'country' => 'Kaliningrad'],
            ['id' => 363, 'prefix' => '3Z', 'country' => 'Poland'],
            ['id' => 364, 'prefix' => 'HF', 'country' => 'Poland'],
            ['id' => 365, 'prefix' => 'SN', 'country' => 'Poland'],
            ['id' => 366, 'prefix' => 'SO', 'country' => 'Poland'],
            ['id' => 367, 'prefix' => 'SP', 'country' => 'Poland'],
            ['id' => 368, 'prefix' => 'SQ', 'country' => 'Poland'],
            ['id' => 369, 'prefix' => 'SR', 'country' => 'Poland'],
            ['id' => 371, 'prefix' => 'GB', 'country' => 'England'],
            ['id' => 372, 'prefix' => 'GC', 'country' => 'Wales'],
            ['id' => 373, 'prefix' => 'GD', 'country' => 'Isle of Man'],
            ['id' => 374, 'prefix' => 'GH', 'country' => 'Jersey'],
            ['id' => 375, 'prefix' => 'GI', 'country' => 'Northern Ireland'],
            ['id' => 376, 'prefix' => 'GJ', 'country' => 'Jersey'],
            ['id' => 377, 'prefix' => 'GM', 'country' => 'Scotland'],
            ['id' => 378, 'prefix' => 'GN', 'country' => 'Northern Ireland'],
            ['id' => 379, 'prefix' => 'GP', 'country' => 'Guernsey & Dependencies'],
            ['id' => 380, 'prefix' => 'GS', 'country' => 'Scotland'],
            ['id' => 381, 'prefix' => 'GT', 'country' => 'Isle of Man'],
            ['id' => 382, 'prefix' => 'GU', 'country' => 'Guernsey & Dependencies'],
            ['id' => 383, 'prefix' => 'GW', 'country' => 'Wales'],
            ['id' => 384, 'prefix' => 'GX', 'country' => 'England'],
            ['id' => 385, 'prefix' => 'HA', 'country' => 'Hungary'],
            ['id' => 386, 'prefix' => 'HG', 'country' => 'Hungary'],
            ['id' => 387, 'prefix' => 'HB1', 'country' => 'Switzerland'],
            ['id' => 388, 'prefix' => 'HB2', 'country' => 'Switzerland'],
            ['id' => 389, 'prefix' => 'HB3', 'country' => 'Switzerland'],
            ['id' => 390, 'prefix' => 'HB4', 'country' => 'Switzerland'],
            ['id' => 391, 'prefix' => 'HB5', 'country' => 'Switzerland'],
            ['id' => 392, 'prefix' => 'HB6', 'country' => 'Switzerland'],
            ['id' => 393, 'prefix' => 'HB7', 'country' => 'Switzerland'],
            ['id' => 394, 'prefix' => 'HB8', 'country' => 'Switzerland'],
            ['id' => 395, 'prefix' => 'HB9', 'country' => 'Switzerland'],
            ['id' => 396, 'prefix' => 'HB0', 'country' => 'Liechtenstein'],
            ['id' => 397, 'prefix' => 'HE', 'country' => 'Switzerland'],
            ['id' => 398, 'prefix' => 'SA', 'country' => 'Sweden'],
            ['id' => 399, 'prefix' => 'SB', 'country' => 'Sweden'],
            ['id' => 400, 'prefix' => 'SC', 'country' => 'Sweden'],
            ['id' => 401, 'prefix' => 'SD', 'country' => 'Sweden'],
            ['id' => 402, 'prefix' => 'SE', 'country' => 'Sweden'],
            ['id' => 403, 'prefix' => 'SH', 'country' => 'Sweden'],
            ['id' => 404, 'prefix' => 'SI', 'country' => 'Sweden'],
            ['id' => 405, 'prefix' => 'SJ', 'country' => 'Sweden'],
            ['id' => 406, 'prefix' => 'SK', 'country' => 'Sweden'],
            ['id' => 407, 'prefix' => 'SL', 'country' => 'Sweden'],
            ['id' => 408, 'prefix' => 'SM', 'country' => 'Sweden'],
            ['id' => 409, 'prefix' => '7S', 'country' => 'Sweden'],
            ['id' => 410, 'prefix' => '8S', 'country' => 'Sweden'],
            ['id' => 411, 'prefix' => 'OM', 'country' => 'Slovakia'],
            ['id' => 412, 'prefix' => 'OE', 'country' => 'Austria'],
            ['id' => 413, 'prefix' => 'S5', 'country' => 'Slovenia'],
            ['id' => 414, 'prefix' => '9A', 'country' => 'Croatia'],
            ['id' => 415, 'prefix' => 'YT', 'country' => 'Serbia'],
            ['id' => 416, 'prefix' => 'YU', 'country' => 'Serbia'],
            ['id' => 417, 'prefix' => 'E7', 'country' => 'Bosnia Herzegovina'],
            ['id' => 418, 'prefix' => 'T9', 'country' => 'Bosnia Herzegovina'],
            ['id' => 419, 'prefix' => 'ON', 'country' => 'Belgium'],
            ['id' => 420, 'prefix' => 'OO', 'country' => 'Belgium'],
            ['id' => 421, 'prefix' => 'OP', 'country' => 'Belgium'],
            ['id' => 422, 'prefix' => 'OQ', 'country' => 'Belgium'],
            ['id' => 423, 'prefix' => 'OR', 'country' => 'Belgium'],
            ['id' => 424, 'prefix' => 'OS', 'country' => 'Belgium'],
            ['id' => 425, 'prefix' => 'OT', 'country' => 'Belgium'],
            ['id' => 426, 'prefix' => 'PA', 'country' => 'Netherlands'],
            ['id' => 427, 'prefix' => 'PB', 'country' => 'Netherlands'],
            ['id' => 428, 'prefix' => 'PC', 'country' => 'Netherlands'],
            ['id' => 429, 'prefix' => 'PD', 'country' => 'Netherlands'],
            ['id' => 430, 'prefix' => 'PE', 'country' => 'Netherlands'],
            ['id' => 431, 'prefix' => 'PH', 'country' => 'Netherlands'],
            ['id' => 432, 'prefix' => 'PI', 'country' => 'Netherlands'],
            ['id' => 433, 'prefix' => 'XP', 'country' => 'Denmark'],
            ['id' => 434, 'prefix' => 'OU', 'country' => 'Denmark'],
            ['id' => 435, 'prefix' => 'OV', 'country' => 'Denmark'],
            ['id' => 436, 'prefix' => 'OW', 'country' => 'Denmark'],
            ['id' => 437, 'prefix' => 'OX', 'country' => 'Greenland'],
            ['id' => 438, 'prefix' => 'OY', 'country' => 'Faroe Islands'],
            ['id' => 439, 'prefix' => 'YO', 'country' => 'Romania'],
            ['id' => 440, 'prefix' => 'YP', 'country' => 'Romania'],
            ['id' => 441, 'prefix' => 'YR', 'country' => 'Romania'],
            ['id' => 442, 'prefix' => 'UR', 'country' => 'Ukraine'],
            ['id' => 443, 'prefix' => 'US', 'country' => 'Ukraine'],
            ['id' => 444, 'prefix' => 'UT', 'country' => 'Ukraine'],
            ['id' => 445, 'prefix' => 'UU', 'country' => 'Ukraine'],
            ['id' => 446, 'prefix' => 'UV', 'country' => 'Ukraine'],
            ['id' => 447, 'prefix' => 'UW', 'country' => 'Ukraine'],
            ['id' => 448, 'prefix' => 'UX', 'country' => 'Ukraine'],
            ['id' => 449, 'prefix' => 'UY', 'country' => 'Ukraine'],
            ['id' => 450, 'prefix' => 'UZ', 'country' => 'Ukraine'],
            ['id' => 451, 'prefix' => 'EM', 'country' => 'Ukraine'],
            ['id' => 452, 'prefix' => 'EN', 'country' => 'Ukraine'],
            ['id' => 453, 'prefix' => 'EO', 'country' => 'Ukraine'],
            ['id' => 454, 'prefix' => 'LY', 'country' => 'Lithuania'],
            ['id' => 455, 'prefix' => 'YL', 'country' => 'Latvia'],
            ['id' => 456, 'prefix' => 'ES', 'country' => 'Estonia'],
            ['id' => 457, 'prefix' => 'OF', 'country' => 'Finland'],
            ['id' => 458, 'prefix' => 'OG', 'country' => 'Finland'],
            ['id' => 459, 'prefix' => 'OH', 'country' => 'Finland'],
            ['id' => 460, 'prefix' => 'OI', 'country' => 'Finland'],
            ['id' => 461, 'prefix' => 'OH0', 'country' => 'Aland Isl'],
            ['id' => 462, 'prefix' => 'OF0', 'country' => 'Aland Isl'],
            ['id' => 463, 'prefix' => 'OG0', 'country' => 'Aland Isl'],
            ['id' => 464, 'prefix' => 'OJ0', 'country' => 'Market Reef'],
            ['id' => 465, 'prefix' => 'OK', 'country' => 'Czech Rep'],
            ['id' => 466, 'prefix' => 'OL', 'country' => 'Czech Rep'],
            ['id' => 467, 'prefix' => 'LX', 'country' => 'Luxembourg'],
            ['id' => 468, 'prefix' => 'LZ', 'country' => 'Bulgaria'],
            ['id' => 469, 'prefix' => '4O', 'country' => 'Montenegro'],
            ['id' => 471, 'prefix' => 'MX', 'country' => 'England'],
            ['id' => 472, 'prefix' => 'MD', 'country' => 'Isle of Man'],
            ['id' => 473, 'prefix' => 'MT', 'country' => 'Isle of Man'],
            ['id' => 474, 'prefix' => 'MI', 'country' => 'Northern Ireland'],
            ['id' => 475, 'prefix' => 'MN', 'country' => 'Northern Ireland'],
            ['id' => 476, 'prefix' => 'MJ', 'country' => 'Jersey'],
            ['id' => 477, 'prefix' => 'MH', 'country' => 'Jersey'],
            ['id' => 478, 'prefix' => 'MM', 'country' => 'Scotland'],
            ['id' => 479, 'prefix' => 'MS', 'country' => 'Scotland'],
            ['id' => 480, 'prefix' => 'MU', 'country' => 'Guernsey & Dependencies'],
            ['id' => 481, 'prefix' => 'MP', 'country' => 'Guernsey & Dependencies'],
            ['id' => 482, 'prefix' => 'MW', 'country' => 'Wales'],
            ['id' => 483, 'prefix' => 'MC', 'country' => 'Wales'],
            ['id' => 484, 'prefix' => '2D', 'country' => 'Isle of Man'],
            ['id' => 485, 'prefix' => '2E', 'country' => 'England'],
            ['id' => 486, 'prefix' => '2I', 'country' => 'Northern Ireland'],
            ['id' => 487, 'prefix' => '2J', 'country' => 'Jersey'],
            ['id' => 488, 'prefix' => '2M', 'country' => 'Scotland'],
            ['id' => 489, 'prefix' => '2U', 'country' => 'Guernsey & Dependencies'],
            ['id' => 490, 'prefix' => '2W', 'country' => 'Wales'],
            ['id' => 491, 'prefix' => 'I1', 'country' => 'Italy'],
            ['id' => 492, 'prefix' => 'I2', 'country' => 'Italy'],
            ['id' => 493, 'prefix' => 'I3', 'country' => 'Italy'],
            ['id' => 494, 'prefix' => 'I4', 'country' => 'Italy'],
            ['id' => 495, 'prefix' => 'I5', 'country' => 'Italy'],
            ['id' => 496, 'prefix' => 'I6', 'country' => 'Italy'],
            ['id' => 497, 'prefix' => 'I7', 'country' => 'Italy'],
            ['id' => 498, 'prefix' => 'I8', 'country' => 'Italy'],
            ['id' => 499, 'prefix' => 'I9', 'country' => 'Italy'],
            ['id' => 500, 'prefix' => 'F0', 'country' => 'France'],
            ['id' => 502, 'prefix' => 'F2', 'country' => 'France'],
            ['id' => 503, 'prefix' => 'F3', 'country' => 'France'],
            ['id' => 504, 'prefix' => 'F4', 'country' => 'France'],
            ['id' => 505, 'prefix' => 'F5', 'country' => 'France'],
            ['id' => 506, 'prefix' => 'F6', 'country' => 'France'],
            ['id' => 507, 'prefix' => 'F7', 'country' => 'France'],
            ['id' => 508, 'prefix' => 'F8', 'country' => 'France'],
            ['id' => 509, 'prefix' => 'F9', 'country' => 'France'],
            ['id' => 510, 'prefix' => 'F1', 'country' => 'France'],
            ['id' => 511, 'prefix' => 'G0', 'country' => 'England'],
            ['id' => 512, 'prefix' => 'G1', 'country' => 'England'],
            ['id' => 513, 'prefix' => 'G2', 'country' => 'England'],
            ['id' => 514, 'prefix' => 'G3', 'country' => 'England'],
            ['id' => 515, 'prefix' => 'G4', 'country' => 'England'],
            ['id' => 516, 'prefix' => 'G5', 'country' => 'England'],
            ['id' => 517, 'prefix' => 'G6', 'country' => 'England'],
            ['id' => 518, 'prefix' => 'G7', 'country' => 'England'],
            ['id' => 519, 'prefix' => 'G8', 'country' => 'England'],
            ['id' => 520, 'prefix' => 'G9', 'country' => 'England'],
            ['id' => 522, 'prefix' => 'M0', 'country' => 'England'],
            ['id' => 523, 'prefix' => 'M1', 'country' => 'England'],
            ['id' => 524, 'prefix' => 'M2', 'country' => 'England'],
            ['id' => 525, 'prefix' => 'M3', 'country' => 'England'],
            ['id' => 526, 'prefix' => 'M4', 'country' => 'England'],
            ['id' => 527, 'prefix' => 'M5', 'country' => 'England'],
            ['id' => 528, 'prefix' => 'M6', 'country' => 'England'],
            ['id' => 529, 'prefix' => 'M7', 'country' => 'England'],
            ['id' => 530, 'prefix' => 'M8', 'country' => 'England'],
            ['id' => 531, 'prefix' => 'M9', 'country' => 'England'],

            // Doplněno: chybějící evropské země reálně dosažitelné na VKV
            // (viz migrace fix_and_extend_prefixes). Pro evropské Rusko jsou
            // uvedeny jen evropské volací oblasti (1/3/4/6); region 2 zůstává
            // Kaliningrad a díky longest-matchi vyhraje (UA2 > UA1 apod.).
            ['id' => 533, 'prefix' => 'LA', 'country' => 'Norway'],
            ['id' => 534, 'prefix' => 'LB', 'country' => 'Norway'],
            ['id' => 535, 'prefix' => 'LC', 'country' => 'Norway'],
            ['id' => 536, 'prefix' => 'LD', 'country' => 'Norway'],
            ['id' => 537, 'prefix' => 'LE', 'country' => 'Norway'],
            ['id' => 538, 'prefix' => 'LF', 'country' => 'Norway'],
            ['id' => 539, 'prefix' => 'LG', 'country' => 'Norway'],
            ['id' => 540, 'prefix' => 'LH', 'country' => 'Norway'],
            ['id' => 541, 'prefix' => 'LI', 'country' => 'Norway'],
            ['id' => 542, 'prefix' => 'LJ', 'country' => 'Norway'],
            ['id' => 543, 'prefix' => 'LK', 'country' => 'Norway'],
            ['id' => 544, 'prefix' => 'LM', 'country' => 'Norway'],
            ['id' => 545, 'prefix' => 'LN', 'country' => 'Norway'],
            ['id' => 546, 'prefix' => 'EU', 'country' => 'Belarus'],
            ['id' => 547, 'prefix' => 'EV', 'country' => 'Belarus'],
            ['id' => 548, 'prefix' => 'EW', 'country' => 'Belarus'],
            ['id' => 549, 'prefix' => 'R1', 'country' => 'European Russia'],
            ['id' => 550, 'prefix' => 'R3', 'country' => 'European Russia'],
            ['id' => 551, 'prefix' => 'R4', 'country' => 'European Russia'],
            ['id' => 552, 'prefix' => 'R6', 'country' => 'European Russia'],
            ['id' => 553, 'prefix' => 'RA1', 'country' => 'European Russia'],
            ['id' => 554, 'prefix' => 'RA3', 'country' => 'European Russia'],
            ['id' => 555, 'prefix' => 'RA4', 'country' => 'European Russia'],
            ['id' => 556, 'prefix' => 'RA6', 'country' => 'European Russia'],
            ['id' => 557, 'prefix' => 'UA1', 'country' => 'European Russia'],
            ['id' => 558, 'prefix' => 'UA3', 'country' => 'European Russia'],
            ['id' => 559, 'prefix' => 'UA4', 'country' => 'European Russia'],
            ['id' => 560, 'prefix' => 'UA6', 'country' => 'European Russia'],
            ['id' => 561, 'prefix' => 'ER', 'country' => 'Moldova'],
            ['id' => 562, 'prefix' => 'EI', 'country' => 'Ireland'],
            ['id' => 563, 'prefix' => 'EJ', 'country' => 'Ireland'],
            ['id' => 564, 'prefix' => 'SV', 'country' => 'Greece'],
            ['id' => 565, 'prefix' => 'SW', 'country' => 'Greece'],
            ['id' => 566, 'prefix' => 'SX', 'country' => 'Greece'],
            ['id' => 567, 'prefix' => 'SY', 'country' => 'Greece'],
            ['id' => 568, 'prefix' => 'SZ', 'country' => 'Greece'],
            ['id' => 569, 'prefix' => 'J4', 'country' => 'Greece'],
        ];
    }
}
